
export const TAROT_CARDS = [
    // Major Arcana
    "The Fool", "The Magician", "The High Priestess", "The Empress", "The Emperor", 
    "The Hierophant", "The Lovers", "The Chariot", "Strength", "The Hermit", 
    "Wheel of Fortune", "Justice", "The Hanged Man", "Death", "Temperance", 
    "The Devil", "The Tower", "The Star", "The Moon", "The Sun", "Judgement", "The World",
    // Wands
    "Ace of Wands", "Two of Wands", "Three of Wands", "Four of Wands", "Five of Wands", 
    "Six of Wands", "Seven of Wands", "Eight of Wands", "Nine of Wands", "Ten of Wands", 
    "Page of Wands", "Knight of Wands", "Queen of Wands", "King of Wands",
    // Cups
    "Ace of Cups", "Two of Cups", "Three of Cups", "Four of Cups", "Five of Cups",
    "Six of Cups", "Seven of Cups", "Eight of Cups", "Nine of Cups", "Ten of Cups",
    "Page of Cups", "Knight of Cups", "Queen of Cups", "King of Cups",
    // Swords
    "Ace of Swords", "Two of Swords", "Three of Swords", "Four of Swords", "Five of Swords",
    "Six of Swords", "Seven of Swords", "Eight of Swords", "Nine of Swords", "Ten of Swords",
    "Page of Swords", "Knight of Swords", "Queen of Swords", "King of Swords",
    // Pentacles
    "Ace of Pentacles", "Two of Pentacles", "Three of Pentacles", "Four of Pentacles", "Five of Pentacles",
    "Six of Pentacles", "Seven of Pentacles", "Eight of Pentacles", "Nine of Pentacles", "Ten of Pentacles",
    "Page of Pentacles", "Knight of Pentacles", "Queen of Pentacles", "King of Pentacles"
];


export const ARCHETYPES = [
    { name: 'The Academic', description: 'Scholar, researcher, professor, or intellectual' },
    { name: 'The Artist', description: 'Creative professional, performer, or aesthetic visionary' },
    { name: 'The Avenger', description: 'Seeks justice or revenge for past wrongs' },
    { name: 'The Broken', description: 'Damaged by trauma, struggling with loss or failure' },
    { name: 'The Careerist', description: 'Ambitious professional focused on advancement and success' },
    { name: 'The Criminal', description: 'Operates outside the law, whether petty or sophisticated' },
    { name: 'The Cursed', description: 'Afflicted by supernatural burden or ongoing misfortune' },
    { name: 'The Deceiver', description: 'Lives through lies, manipulation, or false identity' },
    { name: 'The Descendant', description: 'Inheritor of legacy, bloodline, or family tradition' },
    { name: 'The Detective', description: 'Investigator, seeker of truth, problem solver' },
    { name: 'The Doll', description: 'Controlled by others, lacks agency or independent will' },
    { name: 'The Drifter', description: 'Wanderer without fixed home or permanent attachments' },
    { name: 'The Fixer', description: 'Problem solver who handles difficult situations for others' },
    { name: 'The Occultist', description: 'Student of hidden mysteries and esoteric knowledge' },
    { name: 'The Prophet', description: 'Visionary who sees patterns others miss' },
    { name: 'The Ronin', description: 'Masterless, independent operator without institutional ties' },
    { name: 'The Scientist', description: 'Systematic researcher pursuing empirical understanding' },
    { name: 'The Seeker', description: 'Actively searching for something lost or hidden' },
    { name: 'The Sleeper', description: 'Unaware of supernatural reality around them' },
    { name: 'The Veteran', description: 'Experienced survivor of conflict or hardship' },
];

export const DARK_SECRETS = [
    { name: 'Chosen One', description: 'Believes they are destined for a special purpose or role' },
    { name: 'Curse', description: 'Afflicted by supernatural curse with ongoing consequences' },
    { name: 'Family Secret', description: 'Hidden truth about their bloodline or heritage' },
    { name: 'Forbidden Knowledge', description: 'Possesses dangerous information they shouldn\'t have' },
    { name: 'Guardian', description: 'Secretly protects someone or something important' },
    { name: 'Guilty of Crime', description: 'Committed a serious crime in their past' },
    { name: 'Heir', description: 'Inheritor of something significant and potentially dangerous' },
    { name: 'Mental Illness', description: 'Struggles with psychological condition affecting their reality' },
    { name: 'Occult Experience', description: 'Survived supernatural encounter that changed them' },
    { name: 'Pact with Dark Forces', description: 'Made bargain with dangerous supernatural entity' },
    { name: 'Responsible for Medical Experiments', description: 'Conducted or participated in unethical research' },
    { name: 'Returned from the Other Side', description: 'Came back from death or otherworldly realm' },
    { name: 'Rootless', description: 'Lost all connections to family, home, or identity' },
    { name: 'Strange Disappearance', description: 'Vanished mysteriously for a period of time' },
    { name: 'Victim of Crime', description: 'Survived serious criminal act with lasting impact' },
    { name: 'Victim of Medical Experiments', description: 'Subjected to unethical research or testing' },
    { name: 'Visitations', description: 'Regularly contacted by supernatural entities or visions' },
];

export const DISADVANTAGES = [
    { name: 'Bad Reputation', description: 'You are hated by the public for something you are accused of' },
    { name: 'Broken', description: 'Your Stability can never increase beyond Distressed' },
    { name: 'Competitor', description: 'You have a competitor in the criminal underworld' },
    { name: 'Condemned', description: 'Your fate is sealed and your time is ticking down' },
    { name: 'Cursed', description: 'You are afflicted by a curse' },
    { name: 'Depression', description: 'You are struggling with depression' },
    { name: 'Drug Addict', description: 'You are addicted to hard drugs' },
    { name: 'Experiment Gone Wrong', description: 'You carried out an experiment that went terribly wrong' },
    { name: 'Fanatic', description: 'You are a fervent adherent of an ideology' },
    { name: 'Greedy', description: 'You are driven by an unquenchable desire for money and wealth' },
    { name: 'Guilt', description: 'You carry heavy guilt for your past sins' },
    { name: 'Harassed', description: 'You are part of a harassed minority group' },
    { name: 'Haunted', description: 'You are haunted by supernatural forces' },
    { name: 'Infirm', description: 'You suffer from a dangerous physical disease or condition' },
    { name: 'Involuntary Medium', description: 'You are an open vessel for spirits and demonic entities' },
    { name: 'Jealousy', description: 'You want someone else\'s life for yourself' },
    { name: 'Liar', description: 'You are a compulsive liar' },
    { name: 'Lost Identity', description: 'You have a repressed true identity that resurfaces sometimes' },
    { name: 'Marked', description: 'You are marked by darkness' },
    { name: 'Mental Compulsion', description: 'You have a mental compulsion' },
    { name: 'Nemesis', description: 'You have made an enemy who does everything in their power to take revenge on you' },
    { name: 'Nightmares', description: 'You suffer from recurring nightmares' },
    { name: 'Oath of Revenge', description: 'You are obsessed with taking revenge on someone or an organization' },
    { name: 'Object of Desire', description: 'You ignite unhealthy desires in others' },
    { name: 'Obsession', description: 'You are obsessed by a conspiracy or supernatural phenomenon' },
    { name: 'Owned', description: 'You have fled from someone who kept you as their private property' },
    { name: 'Phobia', description: 'You harbor an overpowering fear of something' },
    { name: 'Rationalist', description: 'Your mind refuses to acknowledge anything except things confirmed by modern science' },
    { name: 'Repressed Memories', description: 'You have repressed an unpleasant event' },
    { name: 'Rival', description: 'You have an ambitious rival, who will do anything to be in your shoes' },
    { name: 'Schizophrenia', description: 'You struggle with psychosis and hallucinations' },
    { name: 'Sexual Neurosis', description: 'Your sexuality is a destructive, controlling force in your life' },
    { name: 'Stalker', description: 'You are hunted by a faceless enemy' },
    { name: 'Victim of Passion', description: 'You have an overwhelming passion for someone or something' },
    { name: 'Wanted', description: 'You are wanted by the authorities' },
];

export const ADVANTAGES = [
    { name: 'Academic Network', description: 'Access to scholarly resources and university connections' },
    { name: 'Access the Dark Net', description: 'Can navigate hidden digital networks and encrypted communications' },
    { name: 'Ace up the Sleeve', description: 'Always has a hidden backup plan or secret resource' },
    { name: 'Analyst', description: 'Exceptional ability to process and interpret complex information' },
    { name: 'Animal Speaker', description: 'Natural affinity for communicating with animals' },
    { name: 'Arcane Researcher', description: 'Skilled at investigating supernatural phenomena and mysteries' },
    { name: 'Artifact', description: 'Possesses a significant supernatural or historically important object' },
    { name: 'Artistic Talent', description: 'Exceptional creative abilities in visual, musical, or performance arts' },
    { name: 'At any Cost', description: 'Willing to sacrifice anything to achieve their goals' },
    { name: 'Authority', description: 'Holds official power or position within an organization' },
    { name: 'Awe-Inspiring', description: 'Natural presence that commands respect and attention' },
    { name: 'Backstab', description: 'Skilled at betrayal and striking when least expected' },
    { name: 'Battlefield Medicine', description: 'Can provide medical care under extreme conditions' },
    { name: 'Body Awareness', description: 'Exceptional understanding of physical form and movement' },
    { name: 'Boss', description: 'Natural leadership abilities and command presence' },
    { name: 'Bound', description: 'Mystically connected to another person, place, or entity' },
    { name: 'Burglar', description: 'Expert at breaking and entering, theft, and infiltration' },
    { name: 'Chameleon', description: 'Exceptional ability to blend in and adopt different personas' },
    { name: 'Character Actor', description: 'Masterful at assuming roles and deceiving others' },
    { name: 'Charismatic Aura', description: 'Naturally draws people and influences their emotions' },
    { name: 'Code of Honor', description: 'Lives by strict moral principles that others respect' },
    { name: 'Collector', description: 'Obsessive gatherer of specific items or information' },
    { name: 'Contagious Insanity', description: 'Can spread madness or irrational behavior to others' },
    { name: 'Crafty', description: 'Clever and resourceful in solving problems' },
    { name: 'Crime Scene Investigator', description: 'Expert at analyzing physical evidence and forensics' },
    { name: 'Cult Leader', description: 'Commands fanatical loyalty from devoted followers' },
    { name: 'Dabbler in the Occult', description: 'Amateur knowledge of supernatural arts and lore' },
    { name: 'Daredevil', description: 'Thrives on dangerous situations and extreme risks' },
    { name: 'Data Retrieval', description: 'Exceptional ability to find and recover digital information' },
    { name: 'Dead Shot', description: 'Exceptional accuracy with ranged weapons' },
    { name: 'Deadly Stare', description: 'Can intimidate or unnerve others through eye contact alone' },
    { name: 'Death Drive', description: 'Compelled toward dangerous or self-destructive situations' },
    { name: 'Desperate', description: 'Extreme circumstances drive exceptional performance' },
    { name: 'Divine', description: 'Blessed with supernatural favor or holy protection' },
    { name: 'Divine Champion', description: 'Chosen warrior of a higher power or sacred cause' },
    { name: 'Dreamer', description: 'Receives visions or insights through dreams and meditation' },
    { name: 'Driver', description: 'Exceptional skill with vehicles and high-speed pursuits' },
    { name: 'Elite Education', description: 'Access to prestigious institutions and high-society connections' },
    { name: 'Elite Sport', description: 'Professional-level athletic ability and physical conditioning' },
    { name: 'Endure Trauma', description: 'Exceptional resilience to physical and psychological damage' },
    { name: 'Enforcer', description: 'Skilled at intimidation and violence on behalf of others' },
    { name: 'Enhanced Awareness', description: 'Heightened perception and ability to notice details' },
    { name: 'Erotic', description: 'Uses sexuality as a tool for manipulation and influence' },
    { name: 'Escape Artist', description: 'Expert at getting out of restraints and confined spaces' },
    { name: 'Exit Strategy', description: 'Always has a planned escape route from dangerous situations' },
    { name: 'Exorcist', description: 'Trained to banish supernatural entities and cleanse possessed individuals' },
    { name: 'Expert', description: 'Exceptional skill and knowledge in a specific field' },
    { name: 'Explosives Expert', description: 'Skilled in creating, disarming, and using explosive devices' },
    { name: 'Extortionist', description: 'Expert at leveraging information and threats for gain' },
    { name: 'Eye for an Eye', description: 'Driven by need for proportional justice and revenge' },
    { name: 'Eye for Detail', description: 'Notices small clues and inconsistencies others miss' },
    { name: 'Fascination', description: 'Can captivate and hold others\' attention completely' },
    { name: 'Fast Talk', description: 'Exceptional ability to persuade through rapid speech' },
    { name: 'Field Agent', description: 'Trained operative with diverse skills for dangerous missions' },
    { name: 'Forbidden Inspiration', description: 'Draws creative power from dark or dangerous sources' },
    { name: 'Forked Tongue', description: 'Master of lies, manipulation, and verbal deception' },
    { name: 'Gang Leader', description: 'Commands respect and loyalty from criminal associates' },
    { name: 'Genius', description: 'Exceptional intelligence and problem-solving ability' },
    { name: 'Good Samaritan', description: 'Compelled to help others, even at personal cost' },
    { name: 'Gritted Teeth', description: 'Can endure pain and hardship through sheer determination' },
    { name: 'Grudge', description: 'Driven by long-held resentment that fuels their actions' },
    { name: 'Hacker', description: 'Expert at infiltrating and manipulating computer systems' },
    { name: 'Hardened', description: 'Emotionally numb to violence and trauma' },
    { name: 'Hunter', description: 'Skilled tracker and predator, whether of animals or people' },
    { name: 'Ice Cold', description: 'Maintains perfect emotional control under pressure' },
    { name: 'Implanted Messages', description: 'Can plant subliminal suggestions in others\' minds' },
    { name: 'Impostor', description: 'Expert at assuming false identities and fooling others' },
    { name: 'Improviser', description: 'Excels at adapting and creating solutions on the fly' },
    { name: 'Influential Friends', description: 'Has powerful allies in high places' },
    { name: 'Inner Power', description: 'Possesses hidden supernatural abilities or potential' },
    { name: 'Instinct', description: 'Relies on gut feelings that are usually correct' },
    { name: 'Interrogator', description: 'Skilled at extracting information through questioning' },
    { name: 'Intimidating', description: 'Natural ability to frighten and cow others' },
    { name: 'Intuitive', description: 'Understands situations without conscious reasoning' },
    { name: 'Inventor', description: 'Creates new devices and solutions to problems' },
    { name: 'Jaded', description: 'Experience has made them cynical but also realistic' },
    { name: 'Keen-Eyed', description: 'Exceptional visual perception and observation skills' },
    { name: 'Lay on Hands', description: 'Can heal others through touch or supernatural means' },
    { name: 'Lightning Fast', description: 'Exceptional speed in movement and reaction' },
    { name: 'Magical Intuition', description: 'Natural understanding of supernatural forces' },
    { name: 'Magnetic Attraction', description: 'Draws others to them through personal magnetism' },
    { name: 'Manhunter', description: 'Expert at tracking and capturing specific individuals' },
    { name: 'Manipulative', description: 'Skilled at controlling others\' emotions and decisions' },
    { name: 'Martial Arts Expert', description: 'Master of unarmed combat techniques' },
    { name: 'Moles', description: 'Has informants placed within important organizations' },
    { name: 'Network of Contacts', description: 'Extensive web of useful connections and allies' },
    { name: 'Notorious', description: 'Fame (or infamy) that opens doors and commands attention' },
    { name: 'Observant', description: 'Notices behavioral patterns and social dynamics' },
    { name: 'Occult Library', description: 'Possesses extensive collection of supernatural knowledge' },
    { name: 'Occult Studies', description: 'Academic understanding of supernatural phenomena' },
    { name: 'Officer', description: 'Military or police training and tactical expertise' },
    { name: 'Opportunist', description: 'Excels at recognizing and exploiting advantageous situations' },
    { name: 'Parkour', description: 'Expert at navigating urban environments through free-running' },
    { name: 'Perpetual Victim', description: 'Others always want to help and protect them' },
    { name: 'Prepared', description: 'Always has the right tool or plan for any situation' },
    { name: 'Puppeteer', description: 'Controls others while remaining hidden behind the scenes' },
    { name: 'Quick Thinker', description: 'Processes information and makes decisions rapidly' },
    { name: 'Rage', description: 'Can channel anger into exceptional physical performance' },
    { name: 'Read a Crowd', description: 'Understands group dynamics and mob psychology' },
    { name: 'Ruthless', description: 'Willing to do whatever it takes without moral constraints' },
    { name: 'Scientist', description: 'Methodical approach to investigation and experimentation' },
    { name: 'Sealed Fate', description: 'Destiny is fixed, bringing both certainty and tragedy' },
    { name: 'Seducer', description: 'Uses charm and attraction to manipulate others' },
    { name: 'Shadow', description: 'Moves unseen and unnoticed through crowds and darkness' },
    { name: 'Sixth Sense', description: 'Perceives dangers and opportunities beyond normal senses' },
    { name: 'Snake Charmer', description: 'Natural ability to calm and control dangerous situations' },
    { name: 'Sneak', description: 'Expert at moving silently and avoiding detection' },
    { name: 'Sniper', description: 'Exceptional accuracy with long-range precision weapons' },
    { name: 'Street Contacts', description: 'Network of informants in criminal and underground circles' },
    { name: 'Streetfighter', description: 'Skilled in brutal, no-rules combat' },
    { name: 'Streetwise', description: 'Understands urban culture and criminal behavior' },
    { name: 'Stubborn', description: 'Refuses to give up or be swayed from their course' },
    { name: 'Survival Instinct', description: 'Natural ability to endure and thrive in harsh conditions' },
    { name: 'Survivalist', description: 'Prepared for worst-case scenarios and disasters' },
    { name: 'Thirst for Knowledge', description: 'Driven to learn and understand everything' },
    { name: 'To the Last Breath', description: 'Fights until physically unable to continue' },
    { name: 'Tracer', description: 'Expert at following trails and tracking movement patterns' },
    { name: 'Vigilant', description: 'Always alert and ready for danger or opportunity' },
    { name: 'Voice of Insanity', description: 'Can drive others to madness through speech' },
    { name: 'Voice of Pain', description: 'Words can inflict psychological and emotional damage' },
    { name: 'Wanderer', description: 'Comfortable traveling and adapting to new environments' },
    { name: 'Watchers', description: 'Has network of observers who report back information' },
    { name: 'Wayfinder', description: 'Never gets lost and can navigate any terrain' },
    { name: 'Weapon Master', description: 'Expert with multiple types of weapons and combat styles' },
    { name: 'Workaholic', description: 'Exceptional dedication and productivity in their profession' },
    { name: 'Worldly', description: 'Extensive knowledge of different cultures and societies' },
];
