import { Arcanum, Rote } from './types';

export const ROTES: Rote[] = [
  // Death Rotes
  { name: 'Corpse Mask', arcanum: Arcanum.Death, rank: 1 },
  { name: 'Death Sight', arcanum: Arcanum.Death, rank: 1 },
  { name: 'Shadow Crafting', arcanum: Arcanum.Death, rank: 1 },
  { name: 'Soul Marks', arcanum: Arcanum.Death, rank: 1 },
  { name: 'Speak with the Dead', arcanum: Arcanum.Death, rank: 1 },
  { name: 'Suppress Aura', arcanum: Arcanum.Death, rank: 1 },
  { name: 'Decay', arcanum: Arcanum.Death, rank: 2 },
  { name: 'Ectoplasmic Shaping', arcanum: Arcanum.Death, rank: 2 },
  { name: 'Foresee Demise', arcanum: Arcanum.Death, rank: 2 },
  { name: 'Ghost Summons', arcanum: Arcanum.Death, rank: 2 },
  { name: 'Withering', arcanum: Arcanum.Death, rank: 2 },
  { name: 'Animate the Dead', arcanum: Arcanum.Death, rank: 3 },
  { name: 'Bind Ghost', arcanum: Arcanum.Death, rank: 3 },
  { name: 'Call the Reaper\'s Name', arcanum: Arcanum.Death, rank: 3 },
  { name: 'Corpse Marionette', arcanum: Arcanum.Death, rank: 3 },
  { name: 'Devouring the Slain', arcanum: Arcanum.Death, rank: 3 },
  { name: 'Enduring Dead', arcanum: Arcanum.Death, rank: 3 },
  { name: 'Ghost-Eater', arcanum: Arcanum.Death, rank: 3 },
  { name: 'Sever the Soul', arcanum: Arcanum.Death, rank: 3 },
  { name: 'Soul Jar', arcanum: Arcanum.Death, rank: 3 },
  { name: 'Suppress Own Life', arcanum: Arcanum.Death, rank: 3 },
  { name: 'Enervation', arcanum: Arcanum.Death, rank: 4 },
  { name: 'Ghost Gate', arcanum: Arcanum.Death, rank: 4 },
  { name: 'Quicken Corpse', arcanum: Arcanum.Death, rank: 4 },
  { name: 'Rotting Flesh, Withering Bones', arcanum: Arcanum.Death, rank: 4 },
  { name: 'Soul-Binding', arcanum: Arcanum.Death, rank: 4 },
  { name: 'Summon the Restless Dead', arcanum: Arcanum.Death, rank: 4 },
  { name: 'Touch of the Grave', arcanum: Arcanum.Death, rank: 4 },
  { name: 'Create Ghost', arcanum: Arcanum.Death, rank: 5 },
  { name: 'Death\'s Gaze', arcanum: Arcanum.Death, rank: 5 },
  { name: 'Empty Body', arcanum: Arcanum.Death, rank: 5 },
  { name: 'Forced Degeneration', arcanum: Arcanum.Death, rank: 5 },
  { name: 'Grim Sight', arcanum: Arcanum.Death, rank: 5 },
  { name: 'Summon the Quickened Dead', arcanum: Arcanum.Death, rank: 5 },

  // Fate Rotes
  { name: 'Exceptional Luck', arcanum: Arcanum.Fate, rank: 1 },
  { name: 'Fabricate Fortune', arcanum: Arcanum.Fate, rank: 1 },
  { name: 'Oaths', arcanum: Arcanum.Fate, rank: 1 },
  { name: 'Reading the Outmost Eddies', arcanum: Arcanum.Fate, rank: 1 },
  { name: 'The Evil Eye', arcanum: Arcanum.Fate, rank: 2 },
  { name: 'Grant Fortune', arcanum: Arcanum.Fate, rank: 2 },
  { name: 'Monkey\'s Paw', arcanum: Arcanum.Fate, rank: 2 },
  { name: 'Shifting the Odds', arcanum: Arcanum.Fate, rank: 2 },
  { name: 'Swarm of Locusts', arcanum: Arcanum.Fate, rank: 2 },
  { name: 'Alter Omen', arcanum: Arcanum.Fate, rank: 3 },
  { name: 'Blessing', arcanum: Arcanum.Fate, rank: 3 },
  { name: 'Curse', arcanum: Arcanum.Fate, rank: 3 },
  { name: 'Diviner\'s Nimbus', arcanum: Arcanum.Fate, rank: 3 },
  { name: 'Grant the Visage of the Fates', arcanum: Arcanum.Fate, rank: 3 },
  { name: 'Occlude Destiny', arcanum: Arcanum.Fate, rank: 3 },
  { name: 'The Perfect Moment', arcanum: Arcanum.Fate, rank: 3 },
  { name: 'Revoke the Inevitable', arcanum: Arcanum.Fate, rank: 3 },
  { name: 'Winds of Chance', arcanum: Arcanum.Fate, rank: 3 },
  { name: 'Break the Chains of Fate', arcanum: Arcanum.Fate, rank: 4 },
  { name: 'Forge Destiny', arcanum: Arcanum.Fate, rank: 4 },
  { name: 'Kiss of the Fortune-Eater', arcanum: Arcanum.Fate, rank: 4 },
  { name: 'Sanctify Oath', arcanum: Arcanum.Fate, rank: 4 },
  { name: 'Forge God', arcanum: Arcanum.Fate, rank: 5 },
  { name: 'Geas', arcanum: Arcanum.Fate, rank: 5 },
  { name: 'Weave Destiny', arcanum: Arcanum.Fate, rank: 5 },

  // Forces Rotes
  { name: 'Control Sound', arcanum: Arcanum.Forces, rank: 1 },
  { name: 'Influence Light', arcanum: Arcanum.Forces, rank: 1 },
  { name: 'Personal Invisibility', arcanum: Arcanum.Forces, rank: 1 },
  { name: 'Tune In', arcanum: Arcanum.Forces, rank: 1 },
  { name: 'Control Weather', arcanum: Arcanum.Forces, rank: 2 },
  { name: 'Increase/Decrease Friction', arcanum: Arcanum.Forces, rank: 2 },
  { name: 'Invisibility', arcanum: Arcanum.Forces, rank: 2 },
  { name: 'Kinetic Blow', arcanum: Arcanum.Forces, rank: 2 },
  { name: 'Telekinesis', arcanum: Arcanum.Forces, rank: 2 },
  { name: 'Augment the Mind and Body', arcanum: Arcanum.Forces, rank: 3 },
  { name: 'Deconstruct', arcanum: Arcanum.Forces, rank: 3 },
  { name: 'Flight', arcanum: Arcanum.Forces, rank: 3 },
  { name: 'Force Field', arcanum: Arcanum.Forces, rank: 3 },
  { name: 'Ghost Shield', arcanum: Arcanum.Forces, rank: 3 },
  { name: 'Levitation', arcanum: Arcanum.Forces, rank: 3 },
  { name: 'Spectrum of the Supernal', arcanum: Arcanum.Forces, rank: 3 },
  { name: 'Transmit and Receive', arcanum: Arcanum.Forces, rank: 3 },
  { name: 'Turn Projectile', arcanum: Arcanum.Forces, rank: 3 },
  { name: 'Electrical Storm', arcanum: Arcanum.Forces, rank: 4 },
  { name: 'Ghost-Storm', arcanum: Arcanum.Forces, rank: 4 },
  { name: 'Major Elemental', arcanum: Arcanum.Forces, rank: 4 },
  { name: 'Telekinetic Storm', arcanum: Arcanum.Forces, rank: 4 },
  { name: 'Control Gravity', arcanum: Arcanum.Forces, rank: 5 },
  { name: 'Elemental Mastery', arcanum: Arcanum.Forces, rank: 5 },
  { name: 'Inferno', arcanum: Arcanum.Forces, rank: 5 },
  { name: 'Nuclear Blast', arcanum: Arcanum.Forces, rank: 5 },
  { name: 'Weather Control', arcanum: Arcanum.Forces, rank: 5 },

  // Life Rotes
  { name: 'Analyze Life', arcanum: Arcanum.Life, rank: 1 },
  { name: 'Healer\'s Trance', arcanum: Arcanum.Life, rank: 1 },
  { name: 'Sense Life', arcanum: Arcanum.Life, rank: 1 },
  { name: 'Body Control', arcanum: Arcanum.Life, rank: 2 },
  { name: 'Cleanse the Body', arcanum: Arcanum.Life, rank: 2 },
  { name: 'First Aid', arcanum: Arcanum.Life, rank: 2 },
  { name: 'Organic Resilience', arcanum: Arcanum.Life, rank: 2 },
  { name: 'Purge Sickness', arcanum: Arcanum.Life, rank: 2 },
  { name: 'Animate plants', arcanum: Arcanum.Life, rank: 3 },
  { name: 'Control the Instincts', arcanum: Arcanum.Life, rank: 3 },
  { name: 'Degeneration', arcanum: Arcanum.Life, rank: 3 },
  { name: 'Entangling plants', arcanum: Arcanum.Life, rank: 3 },
  { name: 'Green Fingers', arcanum: Arcanum.Life, rank: 3 },
  { name: 'Healing Heart', arcanum: Arcanum.Life, rank: 3 },
  { name: 'Hesitation', arcanum: Arcanum.Life, rank: 3 },
  { name: 'Knit', arcanum: Arcanum.Life, rank: 3 },
  { name: 'Rot', arcanum: Arcanum.Life, rank: 3 },
  { name: 'Shapechange', arcanum: Arcanum.Life, rank: 3 },
  { name: 'Weaken the Herd', arcanum: Arcanum.Life, rank: 3 },
  { name: 'Clone', arcanum: Arcanum.Life, rank: 4 },
  { name: 'Contagion', arcanum: Arcanum.Life, rank: 4 },
  { name: 'Dopple-ganger', arcanum: Arcanum.Life, rank: 4 },
  { name: 'Greater Shape-changing', arcanum: Arcanum.Life, rank: 4 },
  { name: 'Life-Summons', arcanum: Arcanum.Life, rank: 4 },
  { name: 'Regeneration', arcanum: Arcanum.Life, rank: 4 },
  { name: 'Create Life', arcanum: Arcanum.Life, rank: 5 },
  { name: 'Fountain of Youth', arcanum: Arcanum.Life, rank: 5 },
  { name: 'Un-aging', arcanum: Arcanum.Life, rank: 5 },
  { name: 'Un-dying', arcanum: Arcanum.Life, rank: 5 },

  // Matter Rotes
  { name: 'Find the Hidden', arcanum: Arcanum.Matter, rank: 1 },
  { name: 'Matter\'s Purity', arcanum: Arcanum.Matter, rank: 1 },
  { name: 'Receive Object', arcanum: Arcanum.Matter, rank: 1 },
  { name: 'Alter Accuracy', arcanum: Arcanum.Matter, rank: 2 },
  { name: 'Alter Weight', arcanum: Arcanum.Matter, rank: 2 },
  { name: 'Steel Windows', arcanum: Arcanum.Matter, rank: 2 },
  { name: 'Transmute Base Metal', arcanum: Arcanum.Matter, rank: 2 },
  { name: 'Wonder Bread', arcanum: Arcanum.Matter, rank: 2 },
  { name: 'Alter Conductivity', arcanum: Arcanum.Matter, rank: 3 },
  { name: 'Alter State', arcanum: Arcanum.Matter, rank: 3 },
  { name: 'Armor-Piercing', arcanum: Arcanum.Matter, rank: 3 },
  { name: 'Enhance Quality', arcanum: Arcanum.Matter, rank: 3 },
  { name: 'Re-shaping', arcanum: Arcanum.Matter, rank: 3 },
  { name: 'The Cracks of the World', arcanum: Arcanum.Matter, rank: 3 },
  { name: 'Transmute Water', arcanum: Arcanum.Matter, rank: 3 },
  { name: 'Alchemist\'s Touch', arcanum: Arcanum.Matter, rank: 4 },
  { name: 'Destroy Matter', arcanum: Arcanum.Matter, rank: 4 },
  { name: 'Golem', arcanum: Arcanum.Matter, rank: 4 },
  { name: 'Transmute Precious Metal', arcanum: Arcanum.Matter, rank: 4 },
  { name: 'Annihilate Matter', arcanum: Arcanum.Matter, rank: 5 },
  { name: 'Create Matter', arcanum: Arcanum.Matter, rank: 5 },
  { name: 'Philosopher\'s Stone', arcanum: Arcanum.Matter, rank: 5 },

  // Mind Rotes
  { name: 'First Impressions', arcanum: Arcanum.Mind, rank: 1 },
  { name: 'Know Thyself', arcanum: Arcanum.Mind, rank: 1 },
  { name: 'Mental Scan', arcanum: Arcanum.Mind, rank: 1 },
  { name: 'One Mind, Two Thoughts', arcanum: Arcanum.Mind, rank: 1 },
  { name: 'Alter Memory', arcanum: Arcanum.Mind, rank: 2 },
  { name: 'Emotional Urging', arcanum: Arcanum.Mind, rank: 2 },
  { name: 'Imposter', arcanum: Arcanum.Mind, rank: 2 },
  { name: 'Psychic Assault', arcanum: Arcanum.Mind, rank: 2 },
  { name: 'Telepathy', arcanum: Arcanum.Mind, rank: 2 },
  { name: 'Aura Perception', arcanum: Arcanum.Mind, rank: 3 },
  { name: 'Goetic Summons', arcanum: Arcanum.Mind, rank: 3 },
  { name: 'Hallucination', arcanum: Arcanum.Mind, rank: 3 },
  { name: 'Incognito', arcanum: Arcanum.Mind, rank: 3 },
  { name: 'Mind Reading', arcanum: Arcanum.Mind, rank: 3 },
  { name: 'Multi-Tasking', arcanum: Arcanum.Mind, rank: 3 },
  { name: 'Sleep', arcanum: Arcanum.Mind, rank: 3 },
  { name: 'Universal Language', arcanum: Arcanum.Mind, rank: 3 },
  { name: 'Beckoning', arcanum: Arcanum.Mind, rank: 4 },
  { name: 'Dreams and Nightmares', arcanum: Arcanum.Mind, rank: 4 },
  { name: 'Greater Goetic Summons', arcanum: Arcanum.Mind, rank: 4 },
  { name: 'Psychic Genesis', arcanum: Arcanum.Mind, rank: 4 },
  { name: 'Read the Depths', arcanum: Arcanum.Mind, rank: 4 },
  { name: 'Amortal', arcanum: Arcanum.Mind, rank: 5 },
  { name: 'Create Mind', arcanum: Arcanum.Mind, rank: 5 },
  { name: 'Possession', arcanum: Arcanum.Mind, rank: 5 },
  { name: 'Tower of Will', arcanum: Arcanum.Mind, rank: 5 },

  // Prime Rotes
  { name: 'Counterspell', arcanum: Arcanum.Prime, rank: 1 },
  { name: 'Dispel Magic', arcanum: Arcanum.Prime, rank: 1 },
  { name: 'Squint', arcanum: Arcanum.Prime, rank: 1 },
  { name: 'Supernal Vision', arcanum: Arcanum.Prime, rank: 1 },
  { name: 'Cloak Nimbus', arcanum: Arcanum.Prime, rank: 2 },
  { name: 'Co-Sign', arcanum: Arcanum.Prime, rank: 2 },
  { name: 'Font of Will', arcanum: Arcanum.Prime, rank: 2 },
  { name: 'Imbue Item', arcanum: Arcanum.Prime, rank: 2 },
  { name: 'Wards', arcanum: Arcanum.Prime, rank: 2 },
  { name: 'Brand of the Hieromagus', arcanum: Arcanum.Prime, rank: 3 },
  { name: 'Consume Tass', arcanum: Arcanum.Prime, rank: 3 },
  { name: 'Dispel Vassal', arcanum: Arcanum.Prime, rank: 3 },
  { name: 'Imbue the Soul', arcanum: Arcanum.Prime, rank: 3 },
  { name: 'Scour the Soul\'s Taint', arcanum: Arcanum.Prime, rank: 3 },
  { name: 'Siphon Integrity', arcanum: Arcanum.Prime, rank: 3 },
  { name: 'Supernal Dispellation', arcanum: Arcanum.Prime, rank: 3 },
  { name: 'Word of Command', arcanum: Arcanum.Prime, rank: 3 },
  { name: 'Create Tass', arcanum: Arcanum.Prime, rank: 4 },
  { name: 'Ley Lines', arcanum: Arcanum.Prime, rank: 4 },
  { name: 'Soul-Flaying', arcanum: Arcanum.Prime, rank: 4 },
  { name: 'Supernal Wards', arcanum: Arcanum.Prime, rank: 4 },
  { name: 'Create Demesne', arcanum: Arcanum.Prime, rank: 5 },
  { name: 'Forge the Soul', arcanum: Arcanum.Prime, rank: 5 },
  { name: 'Hallow', arcanum: Arcanum.Prime, rank: 5 },
  { name: 'Words of Power', arcanum: Arcanum.Prime, rank: 5 },

  // Space Rotes
  { name: 'Correspondence', arcanum: Arcanum.Space, rank: 1 },
  { name: 'Scry', arcanum: Arcanum.Space, rank: 1 },
  { name: 'Spatial Map', arcanum: Arcanum.Space, rank: 1 },
  { name: 'Ban', arcanum: Arcanum.Space, rank: 2 },
  { name: 'Co-location', arcanum: Arcanum.Space, rank: 2 },
  { name: 'Portal', arcanum: Arcanum.Space, rank: 2 },
  { name: 'Teleportation', arcanum: Arcanum.Space, rank: 2 },
  { name: 'Unseen Aegis', arcanum: Arcanum.Space, rank: 2 },
  { name: 'Ward', arcanum: Arcanum.Space, rank: 2 },
  { name: 'Everywhere', arcanum: Arcanum.Space, rank: 3 },
  { name: 'Hide Space', arcanum: Arcanum.Space, rank: 3 },
  { name: 'Scrying Window', arcanum: Arcanum.Space, rank: 3 },
  { name: 'Secret Room', arcanum: Arcanum.Space, rank: 3 },
  { name: 'Sympathetic Range', arcanum: Arcanum.Space, rank: 3 },
  { name: 'Co-location Assault', arcanum: Arcanum.Space, rank: 4 },
  { name: 'Infinite Spaces', arcanum: Arcanum.Space, rank: 4 },
  { name: 'Worlds Within Worlds', arcanum: Arcanum.Space, rank: 4 },
  { name: 'Chain Teleportation', arcanum: Arcanum.Space, rank: 5 },
  { name: 'Forge Connection', arcanum: Arcanum.Space, rank: 5 },
  { name: 'Labyrinth', arcanum: Arcanum.Space, rank: 5 },
  { name: 'Teleport-Others', arcanum: Arcanum.Space, rank: 5 },

  // Spirit Rotes
  { name: 'Gremlins', arcanum: Arcanum.Spirit, rank: 1 },
  { name: 'Spirit Tongue', arcanum: Arcanum.Spirit, rank: 1 },
  { name: 'Coaxing the Spirits', arcanum: Arcanum.Spirit, rank: 2 },
  { name: 'Command Spirit', arcanum: Arcanum.Spirit, rank: 2 },
  { name: 'Ephemeral Shield', arcanum: Arcanum.Spirit, rank: 2 },
  { name: 'Harmonize', arcanum: Arcanum.Spirit, rank: 2 },
  { name: 'Spirit Road', arcanum: Arcanum.Spirit, rank: 2 },
  { name: 'Bargain with the Spirit', arcanum: Arcanum.Spirit, rank: 3 },
  { name: 'Bind Spirit', arcanum: Arcanum.Spirit, rank: 3 },
  { name: 'Drain Ephemera', arcanum: Arcanum.Spirit, rank: 3 },
  { name: 'Ephemeral Lash', arcanum: Arcanum.Spirit, rank: 3 },
  { name: 'Exorcism', arcanum: Arcanum.Spirit, rank: 3 },
  { name: 'Frighten Spirits', arcanum: Arcanum.Spirit, rank: 3 },
  { name: 'Full-Fledged Manifestation', arcanum: Arcanum.Spirit, rank: 3 },
  { name: 'Howl from Beyond', arcanum: Arcanum.Spirit, rank: 3 },
  { name: 'Reaching', arcanum: Arcanum.Spirit, rank: 3 },
  { name: 'Spirit Guardian', arcanum: Arcanum.Spirit, rank: 3 },
  { name: 'Claim the Spirit', arcanum: Arcanum.Spirit, rank: 4 },
  { name: 'Create Fetish', arcanum: Arcanum.Spirit, rank: 4 },
  { name: 'Spirit-Binder', arcanum: Arcanum.Spirit, rank: 4 },
  { name: 'Spirit Summons', arcanum: Arcanum.Spirit, rank: 4 },
  { name: 'Create Twilight', arcanum: Arcanum.Spirit, rank: 5 },
  { name: 'Forge the Spirit', arcanum: Arcanum.Spirit, rank: 5 },
  { name: 'Go into the Shadow', arcanum: Arcanum.Spirit, rank: 5 },
  { name: 'Ultimate Manifestation', arcanum: Arcanum.Spirit, rank: 5 },

  // Time Rotes
  { name: 'Divination', arcanum: Arcanum.Time, rank: 1 },
  { name: 'Perfect Timing', arcanum: Arcanum.Time, rank: 1 },
  { name: 'Postcognition', arcanum: Arcanum.Time, rank: 1 },
  { name: 'Future Glimpse', arcanum: Arcanum.Time, rank: 2 },
  { name: 'Momentary Flux', arcanum: Arcanum.Time, rank: 2 },
  { name: 'Shield of Chronos', arcanum: Arcanum.Time, rank: 2 },
  { name: 'Veil of Moments', arcanum: Arcanum.Time, rank: 2 },
  { name: 'Augury', arcanum: Arcanum.Time, rank: 3 },
  { name: 'Present as Past', arcanum: Arcanum.Time, rank: 3 },
  { name: 'Temporal Dodge', arcanum: Arcanum.Time, rank: 3 },
  { name: 'Temporal Stutter', arcanum: Arcanum.Time, rank: 3 },
  { name: 'Fore-see the Inevitable', arcanum: Arcanum.Time, rank: 4 },
  { name: 'Prophecy', arcanum: Arcanum.Time, rank: 4 },
  { name: 'Reinforce the Present', arcanum: Arcanum.Time, rank: 4 },
  { name: 'Temporal Summoning', arcanum: Arcanum.Time, rank: 4 },
  { name: 'Erase the Past', arcanum: Arcanum.Time, rank: 5 },
  { name: 'Kiss of the May-fly', arcanum: Arcanum.Time, rank: 5 },
  { name: 'Rewrite the Past', arcanum: Arcanum.Time, rank: 5 },
  { name: 'Stop Time', arcanum: Arcanum.Time, rank: 5 },
];
